### ISSUE TITLE
How do you set homeDirectory?

### ISSUE THREAD

**Issue by fearoffish** [vic/vix#3]
Hi Victor, I've used your repositories as a great start to my m1 nix setup, so thanks very much!

I'm a bit of a nix beginner though, and I'm struggling to set my home-manager homeDirectory. When I attempt it:

```
({ config, pkgs, lib, ... }: {
            home-manager.users."jamievandyke" = {
              home.username = "jamievandyke";
              home.homeDirectory = "/Users/jamievandyke";
```

I get this error:

```
error: The option `home-manager.users.jamievandyke.home.homeDirectory' has conflicting definition values:
       - In `<unknown-file>': "/var/empty"
       - In `<unknown-file>': "/Users/jamievandyke"
```

I can't find where that is set nor know how to override it. If I don't set it then I can't use home-manager for things like gpg, because it needs that directory to not be `/var/empty`. I know I'm probably missing something, could you give me a pointer on what I need to know to figure this out?

This is what I'm currently doing (probably incorrectly) and it builds!

https://github.com/fearoffish/nixpkgs

Thanks

[edit] Added gh url.

**Comment by vic** [comment]
Hey! here's a related issue from someone who seems to have a experienced the same: https://github.com/vic/mk-darwin-system/issues/10 

We should definitely add documentation for that on `mk-darwin-system`.

My homedir is `/v` and it is set here: https://github.com/vic/vix/blob/474f246b944882167c7f6330045b2e7c4c6bac8c/vix/modules/vic/default.nix#L18

**Comment by fearoffish** [comment]
I can confirm (long delay sorry!) that setting it as suggested works:

```
({ config, pkgs, lib, ... }: {
            users.users."myuser".home = "/Users/myuser";
```
